Cs 1388 migrate to spring boot 2.4
extremum-community/extremum-common pull request #295
Opened 2021-01-17 14:44 UTC by rpuch

2021-02-11 08:36 UTC, c4lm approved these changes

2021-02-11 13:11 UTC, Slava96 requested changes

2021-02-11 13:11 UTC, Slava96 commented on extremum-shared-models/src/main/java/io/extremum/sharedmodels/descriptor/Descriptor.java
> -    public boolean equals(Object o) {
Can you guarantee that other projects using Extremum not compare descriptors (or use it in collections where equals called inside)?

2021-02-11 18:01 UTC, rpuch commented on extremum-shared-models/src/main/java/io/extremum/sharedmodels/descriptor/Descriptor.java
> -    public boolean equals(Object o) {
Descriptor comparison using equals() cannot work correctly in all cases. So it is simply an error to implement such an equals() method. If they use equals(), they are already in trouble.

Moreover, this change will happen only in the new branch (1.3) that will have a 'breaking change' announcement.

2021-02-12 07:16 UTC, rpuch commented on extremum-shared-models/src/main/java/io/extremum/sharedmodels/descriptor/Descriptor.java
> -    public boolean equals(Object o) {
Oops, I just rebased over a wrong branch. This change should not be in this PR (and it is not anymore).

2021-02-27 12:09 UTC, merged